### ISSUE TITLE
Support manipulating with character index, and make Point arguments optional

### ISSUE THREAD

**Issue by sunny-chung** [tree-sitter/kotlin-tree-sitter#35]
Currently, tree-sitter works with byte offsets and Points (pairs of row index and column index). However, in Java / Kotlin, most of the time I would only deal with character indices. I can assume "bytes" as character indices, but if there is multi-byte character, e.g. CJK characters, in the string, then it need extra workaround and performance overhead to work. To use tree-sitter "correctly" without such hack, it would be a big headache to maintain a dynamic mapping between character indices and byte offsets. Number of bytes per character of substrings should not be a layer Java/Kotlin developers have to deal with. Maintaining an efficient dynamic mapping may require implementing complicated data structures like red-black trees.

The same pain point also applies to the mandatory use of `Point`.

Please correct if I got anything wrong, as there is very few documentation about tree-sitter APIs.

**Comment by ObserverOfTime** [comment]
Multi-byte character support will be improved in the next release.
But points are required by the core library.
