### ISSUE TITLE
Feature Request: Query direct childrens by range

### ISSUE THREAD

**Issue by sunny-chung** [tree-sitter/kotlin-tree-sitter#36]
It is common requiring to query list of childrens by range. For example, it is demanded in incremental syntax highlighting. Currently, ktreesitter only supports querying single smallest descendant by range, which is not enough.

Also, it is not intuitive that accessing `Node.children` actually brings a significant performance overhead.

The best implementation I can come up with an acceptable performance is as below:
```kotlin
            val it: Node = interestedNode
            val range: IntRange = interestedRange

            val m = it.childCount.toInt()
            // find min index where c.endByte >= range.start
            val startIndex = binarySearchForMinIndexOfValueAtLeast(0 until m, range.start) { i -> it.child(i.toUInt())!!.endByte.toInt() }
            // find max index where c.startByte <= range.endInclusive
            val endIndex = binarySearchForMaxIndexOfValueAtMost(0 until m, range.endInclusive) { i -> it.child(i.toUInt())!!.startByte.toInt() }
            (startIndex .. endIndex).forEach { i ->
                val c = it.child(i.toUInt())!!
                if ((c.startByte.toInt() until c.endByte.toInt()) hasIntersectWith range) {
                    visit(c)
                }
            }

```

I believe this implementation (or any better one) should be included into the library, as it is a common use case.

**Comment by ObserverOfTime** [comment]
If it is such a common use case, a function should be added to the core library.
